import type { AlertListItem, AlertListResponse } from '@pharmaguard/types';
import type { ListAlertsQuery } from '@pharmaguard/validation';
import { getSupabaseAdmin } from '../../database/supabase.js';
import { ApiError } from '../../utils/api-error.js';
import { writeAudit } from '../../utils/audit.js';
import type { Request } from 'express';

/**
 * Alerts Center service (PRD §10.18, TRD §7 Alerts).
 *
 * The default "active" filter shows NEW + READ alerts plus SNOOZED alerts
 * whose snooze window has expired, so a snoozed alert resurfaces
 * automatically. Alerts are generated by alert-engine.service.ts (expiry /
 * low stock) and by the quarantine / recall services (event alerts).
 */

const ALERT_SELECT = `
  id, type, severity, status, title, message, medicine_id, batch_id,
  snoozed_until, resolved_at, created_at,
  medicines(name),
  batches(batch_no)
`;

type AlertRow = {
  id: string;
  type: string;
  severity: string;
  status: string;
  title: string;
  message: string;
  medicine_id: string | null;
  batch_id: string | null;
  snoozed_until: string | null;
  resolved_at: string | null;
  created_at: string;
  medicines: { name: string } | null;
  batches: { batch_no: string } | null;
};

function mapAlert(row: AlertRow): AlertListItem {
  return {
    id: row.id,
    type: row.type as AlertListItem['type'],
    severity: row.severity as AlertListItem['severity'],
    status: row.status as AlertListItem['status'],
    title: row.title,
    message: row.message,
    medicineId: row.medicine_id,
    medicineName: row.medicines?.name ?? null,
    batchId: row.batch_id,
    batchNo: row.batches?.batch_no ?? null,
    snoozedUntil: row.snoozed_until,
    resolvedAt: row.resolved_at,
    createdAt: row.created_at,
  };
}

export async function listAlerts(
  pharmacyId: string,
  query: ListAlertsQuery,
): Promise<AlertListResponse> {
  const supabase = getSupabaseAdmin();

  let listQuery = supabase
    .from('alerts')
    .select(ALERT_SELECT)
    .eq('pharmacy_id', pharmacyId)
    .order('created_at', { ascending: false })
    .range((query.page - 1) * query.pageSize, query.page * query.pageSize - 1);

  if (query.status === 'active') {
    // NEW + READ always; SNOOZED only once its snooze window has passed.
    listQuery = listQuery.or(
      `status.in.(NEW,READ),and(status.eq.SNOOZED,snoozed_until.lte.${new Date().toISOString()})`,
    );
  } else {
    listQuery = listQuery.eq('status', query.status);
  }
  if (query.severity) listQuery = listQuery.eq('severity', query.severity);
  if (query.type) listQuery = listQuery.eq('type', query.type);

  let countQuery = supabase
    .from('alerts')
    .select('id', { count: 'exact', head: true })
    .eq('pharmacy_id', pharmacyId);
  if (query.status === 'active') {
    countQuery = countQuery.or(
      `status.in.(NEW,READ),and(status.eq.SNOOZED,snoozed_until.lte.${new Date().toISOString()})`,
    );
  } else {
    countQuery = countQuery.eq('status', query.status);
  }
  if (query.severity) countQuery = countQuery.eq('severity', query.severity);
  if (query.type) countQuery = countQuery.eq('type', query.type);

  const unreadCountQuery = supabase
    .from('alerts')
    .select('id', { count: 'exact', head: true })
    .eq('pharmacy_id', pharmacyId)
    .eq('status', 'NEW');

  const [listResult, countResult, unreadResult] = await Promise.all([
    listQuery,
    countQuery,
    unreadCountQuery,
  ]);

  if (listResult.error) throw ApiError.internal(`Could not load alerts: ${listResult.error.message}`);
  if (countResult.error) throw ApiError.internal(`Could not count alerts: ${countResult.error.message}`);
  if (unreadResult.error) throw ApiError.internal(`Could not count unread alerts: ${unreadResult.error.message}`);

  return {
    alerts: (listResult.data as unknown as AlertRow[]).map(mapAlert),
    total: countResult.count ?? 0,
    page: query.page,
    pageSize: query.pageSize,
    unreadCount: unreadResult.count ?? 0,
  };
}

/** Loads one alert (scoped to the pharmacy) and returns it mapped. */
async function getAlertRow(pharmacyId: string, alertId: string): Promise<AlertRow> {
  const { data, error } = await getSupabaseAdmin()
    .from('alerts')
    .select(ALERT_SELECT)
    .eq('pharmacy_id', pharmacyId)
    .eq('id', alertId)
    .maybeSingle();
  if (error) throw ApiError.internal(`Could not load the alert: ${error.message}`);
  if (!data) throw ApiError.notFound('Alert not found');
  return data as unknown as AlertRow;
}

export async function markAlertRead(
  pharmacyId: string,
  userId: string,
  alertId: string,
  request?: Request,
): Promise<AlertListItem> {
  const alert = await getAlertRow(pharmacyId, alertId);
  if (alert.status === 'RESOLVED') {
    throw ApiError.conflict('Resolved alerts cannot be marked as read');
  }
  if (alert.status !== 'NEW') {
    return mapAlert(alert); // idempotent for READ/SNOOZED
  }

  const { error } = await getSupabaseAdmin().from('alerts').update({ status: 'READ' }).eq('id', alertId);
  if (error) throw ApiError.internal(`Could not mark the alert as read: ${error.message}`);

  await writeAudit({
    pharmacyId,
    userId,
    action: 'alert.read',
    entityType: 'alert',
    entityId: alertId,
    before: { status: alert.status },
    after: { status: 'READ' },
    request,
  });

  return mapAlert({ ...alert, status: 'READ' });
}

export async function resolveAlert(
  pharmacyId: string,
  userId: string,
  alertId: string,
  request?: Request,
): Promise<AlertListItem> {
  const alert = await getAlertRow(pharmacyId, alertId);
  if (alert.status === 'RESOLVED') {
    throw ApiError.conflict('Alert is already resolved');
  }

  const resolvedAt = new Date().toISOString();
  const { error } = await getSupabaseAdmin()
    .from('alerts')
    .update({ status: 'RESOLVED', resolved_at: resolvedAt, resolved_by: userId })
    .eq('id', alertId);
  if (error) throw ApiError.internal(`Could not resolve the alert: ${error.message}`);

  await writeAudit({
    pharmacyId,
    userId,
    action: 'alert.resolved',
    entityType: 'alert',
    entityId: alertId,
    before: { status: alert.status },
    after: { status: 'RESOLVED' },
    request,
  });

  return mapAlert({ ...alert, status: 'RESOLVED', resolved_at: resolvedAt });
}

export async function snoozeAlert(
  pharmacyId: string,
  userId: string,
  alertId: string,
  days: number,
  request?: Request,
): Promise<AlertListItem> {
  const alert = await getAlertRow(pharmacyId, alertId);
  if (alert.status === 'RESOLVED') {
    throw ApiError.conflict('Resolved alerts cannot be snoozed');
  }

  const snoozedUntil = new Date(Date.now() + days * 86_400_000).toISOString();
  const { error } = await getSupabaseAdmin()
    .from('alerts')
    .update({ status: 'SNOOZED', snoozed_until: snoozedUntil })
    .eq('id', alertId);
  if (error) throw ApiError.internal(`Could not snooze the alert: ${error.message}`);

  await writeAudit({
    pharmacyId,
    userId,
    action: 'alert.snoozed',
    entityType: 'alert',
    entityId: alertId,
    before: { status: alert.status },
    after: { status: 'SNOOZED', snoozedUntil, days },
    request,
  });

  return mapAlert({ ...alert, status: 'SNOOZED', snoozed_until: snoozedUntil });
}
